# Generated by Django 2.2.13 on 2020-06-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaecontrol', '0008_auto_20200618_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
