# Generated by Django 2.2.13 on 2020-06-20 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eaecontrol', '0009_auto_20200620_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'گروه کاربری', 'verbose_name_plural': 'گروه های کاربری'},
        ),
    ]
