# Generated by Django 2.2.13 on 2020-06-20 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eaecontrol', '0010_auto_20200620_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterModelOptions(
            name='timing',
            options={'verbose_name': 'رکورد', 'verbose_name_plural': 'رکورد ها'},
        ),
    ]
