# Generated by Django 2.2.13 on 2020-06-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaecontrol', '0011_auto_20200620_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='lastStatusChangeTime',
            field=models.TimeField(blank=True, null=True, verbose_name='آخرین ساعت تغییر'),
        ),
    ]
